// Auto-generated component and font library
// Generated from SVG assets - DO NOT EDIT MANUALLY
// Build: make library (from src/ directory)
//
// Location: src/elxnk/component_library.h
// Generated by: tools/svg2header.py (or tools/svg_to_lamp_smartv2.py for standalone use)

#ifndef ELXNK_LIBRARY_H
#define ELXNK_LIBRARY_H

#include <string>
#include <vector>
#include <map>

namespace elxnk {

// Lamp command structure
struct LampCommand {
    const char* cmd;
};

// Component definition
struct Component {
    const char* name;
    const LampCommand* commands;
    int count;
};

// Font glyph definition
struct FontGlyph {
    char character;
    const LampCommand* commands;
    int count;
};

// Component: D
static const LampCommand D_commands[] = {
    {"pen up"},
    {"pen move 2 0"},
    {"pen down"},
    {"pen move 2 2"},
    {"pen up"},
    {"pen move 5 0"},
    {"pen down"},
    {"pen move 5 2"},
    {"pen move 2 1"},
    {"pen move 5 0"},
    {"pen up"},
    {"pen move 5 1"},
    {"pen down"},
    {"pen move 2 1"},
    {"pen up"},
    {"pen move 2 1"},
    {"pen down"},
    {"pen move 0 1"},
    {"pen up"},
    {"pen move 5 1"},
    {"pen down"},
    {"pen move 7 1"},
    {"pen up"},
};

// Component: GND
static const LampCommand GND_commands[] = {
    {"pen up"},
    {"pen move 0 1"},
    {"pen down"},
    {"pen move 1 1"},
    {"pen up"},
    {"pen move 1 2"},
    {"pen down"},
    {"pen move 1 2"},
    {"pen up"},
    {"pen move 1 1"},
    {"pen down"},
    {"pen move 1 0"},
    {"pen up"},
    {"pen move 2 1"},
    {"pen down"},
    {"pen move 0 1"},
    {"pen up"},
    {"pen move 1 0"},
    {"pen down"},
    {"pen move 1 0"},
    {"pen up"},
};

// Component: L
static const LampCommand L_commands[] = {
    {"pen up"},
    {"pen move 0 2"},
    {"pen move 0 3"},
    {"pen move 0 5"},
    {"pen move 0 6"},
    {"pen move 0 1"},
    {"pen down"},
    {"pen move 0 0"},
    {"pen up"},
    {"pen move 0 6"},
    {"pen down"},
    {"pen move 0 7"},
    {"pen up"},
};

// Component: NMOS
static const LampCommand NMOS_commands[] = {
    {"pen up"},
    {"pen move 5 3"},
    {"pen down"},
    {"pen move 5 7"},
    {"pen up"},
    {"pen move 5 5"},
    {"pen down"},
    {"pen move 2 5"},
    {"pen up"},
    {"pen move 5 2"},
    {"pen down"},
    {"pen move 5 3"},
    {"pen up"},
    {"pen move 5 4"},
    {"pen down"},
    {"pen move 5 5"},
    {"pen up"},
    {"pen move 5 6"},
    {"pen down"},
    {"pen move 5 7"},
    {"pen up"},
    {"pen move 5 6"},
    {"pen down"},
    {"pen move 8 6"},
    {"pen move 8 3"},
    {"pen move 5 3"},
    {"pen up"},
    {"pen move 6 5"},
    {"pen down"},
    {"pen move 7 4"},
    {"pen move 7 5"},
    {"pen move 6 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 3"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 5"},
    {"pen move 5 5"},
    {"pen up"},
    {"pen move 8 4"},
    {"pen down"},
    {"pen move 8 4"},
    {"pen up"},
    {"pen move 8 4"},
    {"pen down"},
    {"pen move 8 5"},
    {"pen move 8 5"},
    {"pen move 8 4"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 0"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 10"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 0"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 10"},
    {"pen up"},
};

// Component: NPN
static const LampCommand NPN_commands[] = {
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 5 5"},
    {"pen up"},
    {"pen move 5 3"},
    {"pen down"},
    {"pen move 5 7"},
    {"pen up"},
    {"pen move 5 4"},
    {"pen down"},
    {"pen move 7 2"},
    {"pen up"},
    {"pen move 5 5"},
    {"pen down"},
    {"pen move 7 7"},
    {"pen up"},
    {"pen move 6 6"},
    {"pen down"},
    {"pen move 6 6"},
    {"pen move 7 7"},
    {"pen move 6 6"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 0"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 10"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 0"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 10"},
    {"pen up"},
};

// Component: NP_C
static const LampCommand NP_C_commands[] = {
    {"pen up"},
    {"pen move 0 3"},
    {"pen down"},
    {"pen move 4 3"},
    {"pen up"},
    {"pen move 0 4"},
    {"pen down"},
    {"pen move 4 4"},
    {"pen up"},
    {"pen move 2 2"},
    {"pen down"},
    {"pen move 2 0"},
    {"pen up"},
    {"pen move 2 4"},
    {"pen down"},
    {"pen move 2 7"},
    {"pen up"},
};

// Component: OPAMP
static const LampCommand OPAMP_commands[] = {
    {"pen up"},
    {"pen move 12 7"},
    {"pen down"},
    {"pen move 2 2"},
    {"pen move 2 12"},
    {"pen move 12 7"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 3 5"},
    {"pen down"},
    {"pen move 4 5"},
    {"pen up"},
    {"pen move 3 5"},
    {"pen down"},
    {"pen move 3 4"},
    {"pen up"},
    {"pen move 2 10"},
    {"pen down"},
    {"pen move 0 10"},
    {"pen up"},
    {"pen move 3 10"},
    {"pen down"},
    {"pen move 4 10"},
    {"pen up"},
    {"pen move 5 3"},
    {"pen down"},
    {"pen move 5 0"},
    {"pen up"},
    {"pen move 5 11"},
    {"pen down"},
    {"pen move 5 15"},
    {"pen up"},
    {"pen move 12 7"},
    {"pen down"},
    {"pen move 15 7"},
    {"pen up"},
};

// Component: PMOS
static const LampCommand PMOS_commands[] = {
    {"pen up"},
    {"pen move 5 3"},
    {"pen down"},
    {"pen move 5 7"},
    {"pen up"},
    {"pen move 5 5"},
    {"pen down"},
    {"pen move 2 5"},
    {"pen up"},
    {"pen move 5 2"},
    {"pen down"},
    {"pen move 5 3"},
    {"pen up"},
    {"pen move 5 3"},
    {"pen down"},
    {"pen move 8 3"},
    {"pen move 8 6"},
    {"pen move 5 6"},
    {"pen up"},
    {"pen move 5 4"},
    {"pen down"},
    {"pen move 5 5"},
    {"pen up"},
    {"pen move 5 6"},
    {"pen down"},
    {"pen move 5 7"},
    {"pen up"},
    {"pen move 7 5"},
    {"pen down"},
    {"pen move 6 4"},
    {"pen move 6 5"},
    {"pen move 7 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 3"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 5"},
    {"pen move 5 5"},
    {"pen up"},
    {"pen move 8 5"},
    {"pen down"},
    {"pen move 8 5"},
    {"pen up"},
    {"pen move 8 5"},
    {"pen down"},
    {"pen move 8 4"},
    {"pen move 8 4"},
    {"pen move 8 5"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 0"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 10"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 0"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 10"},
    {"pen up"},
};

// Component: PNP
static const LampCommand PNP_commands[] = {
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 5 5"},
    {"pen up"},
    {"pen move 5 3"},
    {"pen down"},
    {"pen move 5 7"},
    {"pen up"},
    {"pen move 5 4"},
    {"pen down"},
    {"pen move 7 2"},
    {"pen up"},
    {"pen move 5 5"},
    {"pen down"},
    {"pen move 7 7"},
    {"pen up"},
    {"pen move 7 6"},
    {"pen down"},
    {"pen move 6 7"},
    {"pen move 6 6"},
    {"pen move 7 6"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 0"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 10"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 7 2"},
    {"pen down"},
    {"pen move 7 0"},
    {"pen up"},
    {"pen move 7 7"},
    {"pen down"},
    {"pen move 7 10"},
    {"pen up"},
};

// Component: P_C
static const LampCommand P_C_commands[] = {
    {"pen up"},
    {"pen move 0 3"},
    {"pen down"},
    {"pen move 4 3"},
    {"pen up"},
    {"pen move 0 1"},
    {"pen down"},
    {"pen move 1 1"},
    {"pen up"},
    {"pen move 1 2"},
    {"pen down"},
    {"pen move 1 1"},
    {"pen up"},
    {"pen move 4 5"},
    {"pen move 2 2"},
    {"pen down"},
    {"pen move 2 0"},
    {"pen up"},
    {"pen move 2 4"},
    {"pen down"},
    {"pen move 2 7"},
    {"pen up"},
};

// Component: R
static const LampCommand R_commands[] = {
    {"pen up"},
    {"pen move 1 1"},
    {"pen down"},
    {"pen move 1 1"},
    {"pen up"},
    {"pen move 1 1"},
    {"pen down"},
    {"pen move 2 1"},
    {"pen move 1 2"},
    {"pen move 0 2"},
    {"pen move 1 3"},
    {"pen up"},
    {"pen move 1 3"},
    {"pen down"},
    {"pen move 2 3"},
    {"pen move 1 3"},
    {"pen move 0 4"},
    {"pen move 1 4"},
    {"pen up"},
    {"pen move 1 4"},
    {"pen down"},
    {"pen move 2 5"},
    {"pen move 1 5"},
    {"pen move 0 5"},
    {"pen move 1 6"},
    {"pen up"},
    {"pen move 1 6"},
    {"pen down"},
    {"pen move 1 6"},
    {"pen up"},
    {"pen move 1 1"},
    {"pen down"},
    {"pen move 1 0"},
    {"pen up"},
    {"pen move 1 6"},
    {"pen down"},
    {"pen move 1 7"},
    {"pen up"},
};

// Component: R_TRIM
static const LampCommand R_TRIM_commands[] = {
    {"pen up"},
    {"pen move 1 1"},
    {"pen down"},
    {"pen move 1 1"},
    {"pen up"},
    {"pen move 1 1"},
    {"pen down"},
    {"pen move 2 1"},
    {"pen move 1 2"},
    {"pen move 0 2"},
    {"pen move 1 3"},
    {"pen up"},
    {"pen move 1 3"},
    {"pen down"},
    {"pen move 2 3"},
    {"pen move 1 3"},
    {"pen move 0 4"},
    {"pen move 1 4"},
    {"pen up"},
    {"pen move 1 4"},
    {"pen down"},
    {"pen move 2 5"},
    {"pen move 1 5"},
    {"pen move 0 5"},
    {"pen move 1 6"},
    {"pen up"},
    {"pen move 1 6"},
    {"pen down"},
    {"pen move 1 6"},
    {"pen up"},
    {"pen move 2 3"},
    {"pen down"},
    {"pen move 3 3"},
    {"pen move 3 4"},
    {"pen move 2 3"},
    {"pen up"},
    {"pen move 3 3"},
    {"pen down"},
    {"pen move 2 3"},
    {"pen up"},
    {"pen move 1 1"},
    {"pen down"},
    {"pen move 1 0"},
    {"pen up"},
    {"pen move 1 6"},
    {"pen down"},
    {"pen move 1 7"},
    {"pen up"},
    {"pen move 3 3"},
    {"pen down"},
    {"pen move 4 3"},
    {"pen up"},
};

// Component: TX
static const LampCommand TX_commands[] = {
    {"pen up"},
    {"pen move 7 2"},
    {"pen move 7 5"},
    {"pen move 7 7"},
    {"pen move 7 10"},
    {"pen move 8 1"},
    {"pen move 8 3"},
    {"pen move 8 6"},
    {"pen move 8 8"},
    {"pen move 9 0"},
    {"pen down"},
    {"pen move 9 10"},
    {"pen up"},
    {"pen move 10 10"},
    {"pen down"},
    {"pen move 10 0"},
    {"pen up"},
    {"pen move 12 0"},
    {"pen move 12 2"},
    {"pen move 12 5"},
    {"pen move 11 1"},
    {"pen move 11 3"},
    {"pen move 11 6"},
    {"pen move 12 7"},
    {"pen move 11 8"},
    {"pen move 7 0"},
    {"pen down"},
    {"pen move 0 0"},
    {"pen up"},
    {"pen move 7 10"},
    {"pen down"},
    {"pen move 0 10"},
    {"pen up"},
    {"pen move 12 0"},
    {"pen down"},
    {"pen move 20 0"},
    {"pen up"},
    {"pen move 12 10"},
    {"pen down"},
    {"pen move 20 10"},
    {"pen up"},
};

// Component: VAC
static const LampCommand VAC_commands[] = {
    {"pen up"},
    {"pen move 2 5"},
    {"pen move 2 5"},
    {"pen move 2 3"},
    {"pen down"},
    {"pen move 3 3"},
    {"pen up"},
    {"pen move 2 3"},
    {"pen down"},
    {"pen move 2 2"},
    {"pen up"},
    {"pen move 2 2"},
    {"pen down"},
    {"pen move 2 0"},
    {"pen up"},
    {"pen move 2 7"},
    {"pen down"},
    {"pen move 2 10"},
    {"pen up"},
    {"pen move 2 6"},
    {"pen down"},
    {"pen move 3 6"},
    {"pen up"},
};

// Component: VAR
static const LampCommand VAR_commands[] = {
    {"pen up"},
    {"pen move 2 1"},
    {"pen down"},
    {"pen move 2 1"},
    {"pen up"},
    {"pen move 2 1"},
    {"pen down"},
    {"pen move 3 1"},
    {"pen move 2 2"},
    {"pen move 1 2"},
    {"pen move 2 3"},
    {"pen up"},
    {"pen move 2 3"},
    {"pen down"},
    {"pen move 3 3"},
    {"pen move 2 3"},
    {"pen move 1 4"},
    {"pen move 2 4"},
    {"pen up"},
    {"pen move 2 4"},
    {"pen down"},
    {"pen move 3 5"},
    {"pen move 2 5"},
    {"pen move 1 5"},
    {"pen move 2 6"},
    {"pen up"},
    {"pen move 2 6"},
    {"pen down"},
    {"pen move 2 6"},
    {"pen up"},
    {"pen move 4 2"},
    {"pen down"},
    {"pen move 4 1"},
    {"pen move 3 1"},
    {"pen move 4 1"},
    {"pen move 0 5"},
    {"pen up"},
    {"pen move 2 1"},
    {"pen down"},
    {"pen move 2 0"},
    {"pen up"},
    {"pen move 2 6"},
    {"pen down"},
    {"pen move 2 7"},
    {"pen up"},
};

// Component: VDC
static const LampCommand VDC_commands[] = {
    {"pen up"},
    {"pen move 1 4"},
    {"pen down"},
    {"pen move 3 4"},
    {"pen up"},
    {"pen move 1 5"},
    {"pen down"},
    {"pen move 1 5"},
    {"pen up"},
    {"pen move 2 5"},
    {"pen down"},
    {"pen move 2 5"},
    {"pen up"},
    {"pen move 3 5"},
    {"pen down"},
    {"pen move 3 5"},
    {"pen up"},
    {"pen move 2 3"},
    {"pen down"},
    {"pen move 3 3"},
    {"pen up"},
    {"pen move 2 3"},
    {"pen down"},
    {"pen move 2 2"},
    {"pen up"},
    {"pen move 2 2"},
    {"pen down"},
    {"pen move 2 0"},
    {"pen up"},
    {"pen move 2 7"},
    {"pen down"},
    {"pen move 2 10"},
    {"pen up"},
    {"pen move 2 6"},
    {"pen down"},
    {"pen move 3 6"},
    {"pen up"},
};

// Component: ZD
static const LampCommand ZD_commands[] = {
    {"pen up"},
    {"pen move 2 0"},
    {"pen down"},
    {"pen move 2 2"},
    {"pen up"},
    {"pen move 5 0"},
    {"pen down"},
    {"pen move 5 2"},
    {"pen move 2 1"},
    {"pen move 5 0"},
    {"pen up"},
    {"pen move 5 1"},
    {"pen down"},
    {"pen move 2 1"},
    {"pen up"},
    {"pen move 2 1"},
    {"pen down"},
    {"pen move 0 1"},
    {"pen up"},
    {"pen move 5 1"},
    {"pen down"},
    {"pen move 7 1"},
    {"pen up"},
    {"pen move 2 2"},
    {"pen down"},
    {"pen move 1 2"},
    {"pen up"},
    {"pen move 3 0"},
    {"pen down"},
    {"pen move 2 0"},
    {"pen up"},
};

// Font: 0
static const LampCommand font_0_commands[] = {
    {"pen up"},
    {"pen move 22 1"},
    {"pen down"},
    {"pen move 33 19"},
    {"pen move 26 27"},
    {"pen move 9 34"},
    {"pen move 2 19"},
    {"pen move 22 1"},
    {"pen up"},
};

// Font: 1
static const LampCommand font_1_commands[] = {
    {"pen up"},
    {"pen move 1 8"},
    {"pen down"},
    {"pen move 15 2"},
    {"pen move 15 29"},
    {"pen move 0 35"},
    {"pen up"},
    {"pen move 15 29"},
    {"pen down"},
    {"pen move 28 27"},
    {"pen up"},
};

// Font: 2
static const LampCommand font_2_commands[] = {
    {"pen up"},
    {"pen move 6 7"},
    {"pen down"},
    {"pen move 17 1"},
    {"pen move 27 11"},
    {"pen move 16 24"},
    {"pen move 10 29"},
    {"pen move 1 38"},
    {"pen up"},
    {"pen move 11 29"},
    {"pen down"},
    {"pen move 34 31"},
    {"pen up"},
};

// Font: 3
static const LampCommand font_3_commands[] = {
    {"pen up"},
    {"pen move 1 1"},
    {"pen down"},
    {"pen move 14 2"},
    {"pen move 23 1"},
    {"pen up"},
    {"pen move 21 3"},
    {"pen down"},
    {"pen move 16 8"},
    {"pen move 8 15"},
    {"pen up"},
    {"pen move 14 14"},
    {"pen down"},
    {"pen move 27 20"},
    {"pen move 0 31"},
    {"pen up"},
};

// Font: 4
static const LampCommand font_4_commands[] = {
    {"pen up"},
    {"pen move 25 0"},
    {"pen down"},
    {"pen move 22 10"},
    {"pen move 23 19"},
    {"pen move 32 21"},
    {"pen up"},
    {"pen move 1 21"},
    {"pen down"},
    {"pen move 23 2"},
    {"pen up"},
    {"pen move 3 19"},
    {"pen down"},
    {"pen move 20 20"},
    {"pen move 19 33"},
    {"pen up"},
};

// Font: 5
static const LampCommand font_5_commands[] = {
    {"pen up"},
    {"pen move 0 30"},
    {"pen down"},
    {"pen move 25 22"},
    {"pen move 15 16"},
    {"pen move 8 13"},
    {"pen move 18 2"},
    {"pen move 33 1"},
    {"pen up"},
};

// Font: 6
static const LampCommand font_6_commands[] = {
    {"pen up"},
    {"pen move 9 31"},
    {"pen down"},
    {"pen move 28 20"},
    {"pen move 23 30"},
    {"pen move 4 29"},
    {"pen move 20 1"},
    {"pen up"},
};

// Font: 7
static const LampCommand font_7_commands[] = {
    {"pen up"},
    {"pen move 27 1"},
    {"pen down"},
    {"pen move 10 32"},
    {"pen up"},
    {"pen move 0 2"},
    {"pen down"},
    {"pen move 24 2"},
    {"pen up"},
};

// Font: 8
static const LampCommand font_8_commands[] = {
    {"pen up"},
    {"pen move 11 18"},
    {"pen down"},
    {"pen move 4 8"},
    {"pen move 19 4"},
    {"pen move 7 22"},
    {"pen move 3 30"},
    {"pen move 13 33"},
    {"pen move 15 18"},
    {"pen up"},
    {"pen move 0 29"},
    {"pen down"},
    {"pen move 2 29"},
    {"pen up"},
};

// Font: 9
static const LampCommand font_9_commands[] = {
    {"pen up"},
    {"pen move 20 15"},
    {"pen down"},
    {"pen move 10 18"},
    {"pen move 2 11"},
    {"pen move 15 1"},
    {"pen move 23 5"},
    {"pen move 21 15"},
    {"pen move 17 30"},
    {"pen up"},
};

// Font: A
static const LampCommand font_A_commands[] = {
    {"pen up"},
    {"pen move 13 1"},
    {"pen down"},
    {"pen move 16 13"},
    {"pen move 5 23"},
    {"pen move 2 16"},
    {"pen move 13 1"},
    {"pen up"},
    {"pen move 18 15"},
    {"pen down"},
    {"pen move 30 20"},
    {"pen up"},
};

// Font: B
static const LampCommand font_B_commands[] = {
    {"pen up"},
    {"pen move 11 0"},
    {"pen down"},
    {"pen move 5 26"},
    {"pen move 12 20"},
    {"pen move 22 17"},
    {"pen move 12 36"},
    {"pen move 4 27"},
    {"pen up"},
    {"pen move 0 35"},
    {"pen down"},
    {"pen move 1 35"},
    {"pen up"},
};

// Font: C
static const LampCommand font_C_commands[] = {
    {"pen up"},
    {"pen move 24 17"},
    {"pen down"},
    {"pen move 4 23"},
    {"pen move 2 12"},
    {"pen move 14 6"},
    {"pen up"},
};

// Font: D
static const LampCommand font_D_commands[] = {
    {"pen up"},
    {"pen move 27 0"},
    {"pen down"},
    {"pen move 25 15"},
    {"pen move 23 21"},
    {"pen move 18 28"},
    {"pen move 2 37"},
    {"pen move 15 14"},
    {"pen move 21 22"},
    {"pen up"},
    {"pen move 22 22"},
    {"pen down"},
    {"pen move 24 28"},
    {"pen move 28 37"},
    {"pen move 39 32"},
    {"pen up"},
};

// Font: E
static const LampCommand font_E_commands[] = {
    {"pen up"},
    {"pen move 1 15"},
    {"pen down"},
    {"pen move 6 4"},
    {"pen move 13 3"},
    {"pen move 2 19"},
    {"pen move 24 16"},
    {"pen up"},
};

// Font: F
static const LampCommand font_F_commands[] = {
    {"pen up"},
    {"pen move 0 52"},
    {"pen down"},
    {"pen move 9 29"},
    {"pen move 11 21"},
    {"pen move 12 10"},
    {"pen move 23 6"},
    {"pen up"},
    {"pen move 11 21"},
    {"pen down"},
    {"pen move 22 21"},
    {"pen up"},
};

// Font: G
static const LampCommand font_G_commands[] = {
    {"pen up"},
    {"pen move 25 15"},
    {"pen down"},
    {"pen move 19 18"},
    {"pen move 7 20"},
    {"pen move 24 2"},
    {"pen move 26 9"},
    {"pen move 25 16"},
    {"pen move 24 23"},
    {"pen move 16 37"},
    {"pen move 1 32"},
    {"pen up"},
};

// Font: H
static const LampCommand font_H_commands[] = {
    {"pen up"},
    {"pen move 8 0"},
    {"pen down"},
    {"pen move 2 32"},
    {"pen up"},
    {"pen move 2 37"},
    {"pen down"},
    {"pen move 13 27"},
    {"pen move 21 19"},
    {"pen move 33 32"},
    {"pen move 39 25"},
    {"pen up"},
    {"pen move 1 36"},
    {"pen down"},
    {"pen move 2 37"},
    {"pen up"},
};

// Font: I
static const LampCommand font_I_commands[] = {
    {"pen up"},
    {"pen move 8 0"},
    {"pen down"},
    {"pen move 8 1"},
    {"pen up"},
    {"pen move 4 15"},
    {"pen down"},
    {"pen move 19 29"},
    {"pen up"},
};

// Font: J
static const LampCommand font_J_commands[] = {
    {"pen up"},
    {"pen move 16 0"},
    {"pen down"},
    {"pen move 14 19"},
    {"pen move 13 28"},
    {"pen move 0 35"},
    {"pen up"},
};

// Font: K
static const LampCommand font_K_commands[] = {
    {"pen up"},
    {"pen move 5 0"},
    {"pen down"},
    {"pen move 3 20"},
    {"pen move 1 35"},
    {"pen up"},
    {"pen move 21 10"},
    {"pen down"},
    {"pen move 4 28"},
    {"pen up"},
    {"pen move 8 25"},
    {"pen down"},
    {"pen move 22 33"},
    {"pen move 33 35"},
    {"pen up"},
};

// Font: L
static const LampCommand font_L_commands[] = {
    {"pen up"},
    {"pen move 5 0"},
    {"pen down"},
    {"pen move 1 27"},
    {"pen move 3 36"},
    {"pen move 20 31"},
    {"pen up"},
};

// Font: M
static const LampCommand font_M_commands[] = {
    {"pen up"},
    {"pen move 3 1"},
    {"pen down"},
    {"pen move 1 11"},
    {"pen move 2 18"},
    {"pen move 17 2"},
    {"pen move 22 17"},
    {"pen move 35 2"},
    {"pen move 38 9"},
    {"pen move 50 15"},
    {"pen move 53 11"},
    {"pen up"},
};

// Font: N
static const LampCommand font_N_commands[] = {
    {"pen up"},
    {"pen move 4 0"},
    {"pen down"},
    {"pen move 2 9"},
    {"pen move 1 19"},
    {"pen up"},
    {"pen move 4 16"},
    {"pen down"},
    {"pen move 10 10"},
    {"pen move 16 6"},
    {"pen move 18 10"},
    {"pen move 21 18"},
    {"pen move 34 17"},
    {"pen up"},
};

// Font: O
static const LampCommand font_O_commands[] = {
    {"pen up"},
    {"pen move 11 2"},
    {"pen down"},
    {"pen move 21 10"},
    {"pen move 8 22"},
    {"pen move 11 2"},
    {"pen up"},
};

// Font: P
static const LampCommand font_P_commands[] = {
    {"pen up"},
    {"pen move 7 1"},
    {"pen down"},
    {"pen move 6 10"},
    {"pen move 6 17"},
    {"pen move 12 23"},
    {"pen move 20 19"},
    {"pen move 27 4"},
    {"pen move 17 4"},
    {"pen move 8 15"},
    {"pen up"},
    {"pen move 5 22"},
    {"pen down"},
    {"pen move 1 38"},
    {"pen up"},
};

// Font: Q
static const LampCommand font_Q_commands[] = {
    {"pen up"},
    {"pen move 17 16"},
    {"pen down"},
    {"pen move 12 21"},
    {"pen move 3 23"},
    {"pen move 19 2"},
    {"pen move 19 15"},
    {"pen move 16 28"},
    {"pen move 13 38"},
    {"pen move 13 41"},
    {"pen up"},
};

// Font: R
static const LampCommand font_R_commands[] = {
    {"pen up"},
    {"pen move 2 15"},
    {"pen down"},
    {"pen move 9 11"},
    {"pen move 22 1"},
    {"pen up"},
    {"pen move 5 1"},
    {"pen down"},
    {"pen move 2 11"},
    {"pen up"},
    {"pen move 1 14"},
    {"pen down"},
    {"pen move 2 15"},
    {"pen up"},
    {"pen move 4 17"},
    {"pen down"},
    {"pen move 4 21"},
    {"pen up"},
};

// Font: S
static const LampCommand font_S_commands[] = {
    {"pen up"},
    {"pen move 6 1"},
    {"pen down"},
    {"pen move 8 21"},
    {"pen move 2 31"},
    {"pen up"},
};

// Font: T
static const LampCommand font_T_commands[] = {
    {"pen up"},
    {"pen move 12 0"},
    {"pen down"},
    {"pen move 23 10"},
    {"pen up"},
    {"pen move 9 10"},
    {"pen down"},
    {"pen move 0 12"},
    {"pen up"},
    {"pen move 6 13"},
    {"pen down"},
    {"pen move 5 20"},
    {"pen move 13 32"},
    {"pen move 19 27"},
    {"pen up"},
};

// Font: U
static const LampCommand font_U_commands[] = {
    {"pen up"},
    {"pen move 5 0"},
    {"pen down"},
    {"pen move 1 13"},
    {"pen move 6 20"},
    {"pen move 14 14"},
    {"pen move 22 0"},
    {"pen up"},
    {"pen move 20 9"},
    {"pen down"},
    {"pen move 33 15"},
    {"pen up"},
};

// Font: V
static const LampCommand font_V_commands[] = {
    {"pen up"},
    {"pen move 25 1"},
    {"pen down"},
    {"pen move 7 22"},
    {"pen move 2 2"},
    {"pen up"},
};

// Font: W
static const LampCommand font_W_commands[] = {
    {"pen up"},
    {"pen move 39 0"},
    {"pen down"},
    {"pen move 32 14"},
    {"pen move 28 20"},
    {"pen move 23 13"},
    {"pen move 20 7"},
    {"pen move 8 23"},
    {"pen move 1 5"},
    {"pen up"},
    {"pen move 0 5"},
    {"pen down"},
    {"pen move 1 5"},
    {"pen up"},
};

// Font: X
static const LampCommand font_X_commands[] = {
    {"pen up"},
    {"pen move 4 1"},
    {"pen down"},
    {"pen move 10 14"},
    {"pen move 33 15"},
    {"pen up"},
    {"pen move 21 1"},
    {"pen down"},
    {"pen move 11 14"},
    {"pen up"},
    {"pen move 10 14"},
    {"pen down"},
    {"pen move 1 23"},
    {"pen up"},
};

// Font: Y
static const LampCommand font_Y_commands[] = {
    {"pen up"},
    {"pen move 26 0"},
    {"pen down"},
    {"pen move 21 14"},
    {"pen move 18 23"},
    {"pen move 14 39"},
    {"pen up"},
    {"pen move 7 1"},
    {"pen down"},
    {"pen move 3 10"},
    {"pen move 4 18"},
    {"pen move 21 15"},
    {"pen up"},
    {"pen move 0 16"},
    {"pen down"},
    {"pen move 2 16"},
    {"pen up"},
};

// Font: Z
static const LampCommand font_Z_commands[] = {
    {"pen up"},
    {"pen move 3 2"},
    {"pen down"},
    {"pen move 20 3"},
    {"pen move 1 26"},
    {"pen up"},
    {"pen move 21 1"},
    {"pen down"},
    {"pen move 20 2"},
    {"pen up"},
    {"pen move 32 18"},
    {"pen down"},
    {"pen move 9 21"},
    {"pen up"},
};

// Component lookup table
static const Component COMPONENTS[] = {
    {"D", D_commands, 23},
    {"GND", GND_commands, 21},
    {"L", L_commands, 13},
    {"NMOS", NMOS_commands, 76},
    {"NPN", NPN_commands, 47},
    {"NP_C", NP_C_commands, 17},
    {"OPAMP", OPAMP_commands, 39},
    {"PMOS", PMOS_commands, 76},
    {"PNP", PNP_commands, 47},
    {"P_C", P_C_commands, 22},
    {"R", R_commands, 38},
    {"R_TRIM", R_TRIM_commands, 52},
    {"TX", TX_commands, 41},
    {"VAC", VAC_commands, 23},
    {"VAR", VAR_commands, 45},
    {"VDC", VDC_commands, 37},
    {"ZD", ZD_commands, 31},
};

static const int COMPONENT_COUNT = 17;

// Font glyph lookup table
static const FontGlyph FONT_GLYPHS[] = {
    {'0', font_0_commands, 9},
    {'1', font_1_commands, 11},
    {'2', font_2_commands, 13},
    {'3', font_3_commands, 16},
    {'4', font_4_commands, 16},
    {'5', font_5_commands, 9},
    {'6', font_6_commands, 8},
    {'7', font_7_commands, 9},
    {'8', font_8_commands, 14},
    {'9', font_9_commands, 10},
    {'A', font_A_commands, 12},
    {'B', font_B_commands, 13},
    {'C', font_C_commands, 7},
    {'D', font_D_commands, 16},
    {'E', font_E_commands, 8},
    {'F', font_F_commands, 12},
    {'G', font_G_commands, 12},
    {'H', font_H_commands, 16},
    {'I', font_I_commands, 9},
    {'J', font_J_commands, 7},
    {'K', font_K_commands, 15},
    {'L', font_L_commands, 7},
    {'M', font_M_commands, 12},
    {'N', font_N_commands, 14},
    {'O', font_O_commands, 7},
    {'P', font_P_commands, 15},
    {'Q', font_Q_commands, 11},
    {'R', font_R_commands, 18},
    {'S', font_S_commands, 6},
    {'T', font_T_commands, 15},
    {'U', font_U_commands, 12},
    {'V', font_V_commands, 6},
    {'W', font_W_commands, 14},
    {'X', font_X_commands, 14},
    {'Y', font_Y_commands, 17},
    {'Z', font_Z_commands, 14},
};

static const int FONT_GLYPH_COUNT = 36;

// Helper functions
inline const Component* find_component(const char* name) {
    for (int i = 0; i < COMPONENT_COUNT; i++) {
        if (strcmp(COMPONENTS[i].name, name) == 0) {
            return &COMPONENTS[i];
        }
    }
    return nullptr;
}

inline const FontGlyph* find_glyph(char c) {
    for (int i = 0; i < FONT_GLYPH_COUNT; i++) {
        if (FONT_GLYPHS[i].character == c) {
            return &FONT_GLYPHS[i];
        }
    }
    return nullptr;
}

} // namespace elxnk

#endif // ELXNK_LIBRARY_H
